# Generated by Django 4.0.3 on 2022-04-09 04:45

from django.db import migrations, models
import django.db.models.deletion
import market.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.FloatField()),
                ('stocks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=market.helpers.RandomFileName('photo'))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.productcategory')),
            ],
        ),
    ]
