# Generated by Django 4.0.3 on 2022-04-09 05:40

from django.db import migrations, models
import market.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=market.helpers.RandomFileName('')),
        ),
    ]
